data: data/yolo_detection/dataset_detection.yaml
model: models/yolo26m.pt
project: outputs/training
name: yolo26m_detection
task: detect
device: cuda
epochs: 50
imgsz: 1024
batch: 8
workers: 8
fraction: 0.2
mosaic: 0.0
fliplr: 0.0
erasing: 0.0
translate: 0.02
scale: 0.05
cos_lr: true
save_period: 1
